export { AvatarAddSvg } from "./AvatarAddSvg";
export { CreatePostsSvg } from "./CreatePostsSvg";
export { PostsSvg } from "./PostsSvg";
export { ProfileSvg } from "./ProfileSvg";
export { LogOutSvg } from "./LogOutSvg";
export { MapPinSvg } from "./MapPinSvg";
export { ArrowLeftSvg } from "./ArrowLeftSvg";
export { CommentSvg } from "./CommentSvg";
export { SendMessageSvg } from "./SendMessageSvg";
